declare
  
  begin
    execute immediate 'truncate table LEFT_TOP_HEAD_TEMP';
    execute immediate 'truncate table LEFT_TOP_Y_TEMP';
    
  INSERT INTO LEFT_TOP_HEAD_TEMP (TITLE,CATEGORYAXISLABEL,VALUEAXISLABEL) VALUES ('三日产线备料进度(开发中)','样本数据','单位(%)');
  COMMIT;
  
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃南线','2018-05-12',95,1);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃南线','2018-05-13',24,1);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃南线','2018-05-14',22,1);
  
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭北线','2018-05-12',6,2);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭北线','2018-05-13',9,2);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭北线','2018-05-14',12,2);
  
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃北线','2018-05-12',78,3);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃北线','2018-05-13',70,3);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('骏铃北线','2018-05-14',78,3);
  
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭南线','2018-05-12',10,4);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭南线','2018-05-13',20,4);
  INSERT INTO LEFT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE) VALUES ('帅岭南线','2018-05-14',20,4);
  COMMIT;

  execute immediate 'truncate table LEFT_TOP_HEAD';
  execute immediate 'alter table LEFT_TOP_HEAD nologging';
  insert /*+append*/ into LEFT_TOP_HEAD select * from LEFT_TOP_HEAD_TEMP;
  commit;
  
  execute immediate 'truncate table LEFT_TOP_Y';
  execute immediate 'alter table LEFT_TOP_Y nologging';
  insert /*+append*/ into LEFT_TOP_Y select * from LEFT_TOP_Y_TEMP;
  commit;
  end;