declare

begin
  
  begin 
      execute immediate 'truncate table RIGHT_TOP_HEAD_TEMP';
      execute immediate 'truncate table RIGHT_TOP_Y_TEMP';
      
      INSERT INTO RIGHT_TOP_HEAD_TEMP (TITLE,CATEGORYAXISLABEL,VALUEAXISLABEL,TYPE) VALUES ('标题1','标题2','Y轴(%)','right_top');
      COMMIT;
    
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点01',49.9,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点02',71.5,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点03',106.4,1,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点04',129.2,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点05',144.0,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点06',176.0,1,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点07',135.6,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点08',148.5,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点09',216.4,1,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点10',194.1,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点11',95.6,1,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标1','节点12',54.4,1,'right_top');

      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点01',83.6,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点02',78.8,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点03',98.5,2,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点04',93.4,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点05',106.0,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点06',84.5,2,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点07',105.0,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点08',104.3,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点09',91.2,2,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点10',83.5,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点11',106.6,2,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标2','节点12',92.3,2,'right_top');

      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点01',48.9,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点02',38.8,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点03',39.3,3,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点04',41.4,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点05',47.0,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点06',48.3,3,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点07',59.0,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点08',59.6,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点09',52.4,3,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点10',65.2,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点11',59.3,3,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标3','节点12',51.2,3,'right_top');	  
    
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点01',42.4,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点02',33.2,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点03',34.5,4,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点04',39.7,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点05',52.6,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点06',75.5,4,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点07',57.4,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点08',60.4,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点09',47.6,4,'right_top');
	  INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点10',39.1,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点11',46.8,4,'right_top');
      INSERT INTO RIGHT_TOP_Y_TEMP(CATEGORIES,X,QUANTITY,LINE,TYPE) VALUES ('指标4','节点12',51.1,4,'right_top');

      COMMIT;

    execute immediate 'truncate table RIGHT_TOP_HEAD';
    execute immediate 'alter table RIGHT_TOP_HEAD nologging';
    insert /*+append*/ into RIGHT_TOP_HEAD select * from RIGHT_TOP_HEAD_TEMP;
    commit;
    
    execute immediate 'truncate table RIGHT_TOP_Y';
    execute immediate 'alter table RIGHT_TOP_Y nologging';
    insert /*+append*/ into RIGHT_TOP_Y select * from RIGHT_TOP_Y_TEMP;
    commit;
    end;
  
end;