declare

begin

    execute immediate 'truncate table LEFT_BOTTOM_HEAD_TEMP';
    execute immediate 'truncate table LEFT_BOTTOM_Y_TEMP';
    
    INSERT INTO LEFT_BOTTOM_HEAD_TEMP (TITLE,CATEGORYAXISLABEL,VALUEAXISLABEL,NUMBERAXIS,PILLAR,LINE) 
		VALUES ('标题1','标题2','左Y轴','右Y轴','指标一','指标二');
    COMMIT;
    
    INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点1', 92669.20,39.01,1);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点2', 95790.47,0,2);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点3', 106187.80,45.39,3);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点4', 128530.88,30.46,4);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点5', 156608.82,27.50,5);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点6', 193003.08,24.34,6);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点7', 255800.38,19.90,7);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点8', 335302.66,19.48,8);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点9', 549877.54,12.67,9);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点10',1251596.81,10.40,10);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点11',1321658.11,10.02,11);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点12',1917721.09,11.97,12);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点13',2728598.10,20.51,13);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点14',3418600.00,30.01,14);
	INSERT INTO LEFT_BOTTOM_Y_TEMP(X,PILLAR_QUANTITY,LINE_QUANTITY,LINE) VALUES ('节点15',4092200.00,0,15);
    COMMIT;

    execute immediate 'truncate table LEFT_BOTTOM_HEAD';
    execute immediate 'alter table LEFT_BOTTOM_HEAD nologging';
    insert /*+append*/ into LEFT_BOTTOM_HEAD select * from LEFT_BOTTOM_HEAD_TEMP;
    commit;
    
    execute immediate 'truncate table LEFT_BOTTOM_Y';
    execute immediate 'alter table LEFT_BOTTOM_Y nologging';
    insert /*+append*/ into LEFT_BOTTOM_Y select * from LEFT_BOTTOM_Y_TEMP;
    commit;
  
end;